"""Where the tests reach past an interface, counted rather than remembered.

The design guide's rule is that a test reaches the names a caller
reaches, so an underscore reach-in is a review flag: either the module
is missing an interface callers need, or the test pins a detail that is
free to change. #210's M6 acts on that rule across the whole suite, and
acting on it needs a census rather than an impression.

What counts as a site: a NAME token spelled `_x` (one leading
underscore, then a letter) immediately after an `OP` `.`, anywhere under
`tests/`. A tokenizer rather than an AST walk because the question is
lexical: `session._opened_at` is a reach-in whatever the expression in
front of the dot evaluates to, and a walk that resolved receivers would
have to know what every fixture returns.

What does not count: `self._x` and `cls._x`. A test file's own fakes and
its own test classes keep private state of their own, and that state is
theirs; reaching for it crosses no interface. Those are counted
separately and reported, so the exclusion is visible rather than
silent.

    uv run python -m tests.tools.reach_ins            # summary
    uv run python -m tests.tools.reach_ins --by-site  # file:line per site
    uv run python -m tests.tools.reach_ins --json     # the whole census

`manifest_of` renders the same census as the committed manifest reads
it, `tests/census/reach-ins.txt`, which
`tests/census/test_reach_ins.py` diffs against a fresh render on every
change. The manifest records what is there and endorses none of it:
freezing the census is what makes the next reach-in arrive as a named
diff line, and the reduction is #531 M3's, after #482 and #488 M1.

The before-and-after numbers this produces are recorded in the
implementation doc of
`docs/plans/2026-08-19-governance-simplification.md`.
"""

from __future__ import annotations

import argparse
import io
import json
import re
import subprocess
import sys
import token
import tokenize
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path

PRIVATE = re.compile(r"^_[A-Za-z]")
"""One leading underscore then a letter: `_x`, never `__x__` or `_`."""

OWN_STATE = frozenset({"self", "cls"})
"""Receivers whose private state is the reading file's own."""

# What the manifest says about itself, so a reader who opens it first
# knows what it is, what regenerates it, and what it does not claim.
MANIFEST_HEADER = (
    "# Every reach-in the test suite makes, counted. Generated by\n"
    "# tests/census/test_reach_ins.py; do not edit by hand.\n"
    "# Regenerate from vinga-server/ with\n"
    "# `uv run python -m tests.census.test_reach_ins`.\n"
    "#\n"
    "# One line per distinct pair: path  name  sites. No positions, so a\n"
    "# change that only shifts a line leaves this file alone, while the\n"
    "# count moves whenever the number of reaches at that pair does. The\n"
    "# file:line of every site comes from the census itself,\n"
    "# `uv run python -m tests.tools.reach_ins --by-site`.\n"
    "#\n"
    "# This file records what is there. It freezes the census rather\n"
    "# than endorsing it: a green run means nothing arrived unnamed, not\n"
    "# that the number is right. The reduction is #531 M3's, after #482\n"
    "# and #488 M1.\n"
)


class Unwalkable(ValueError):
    """A root `git ls-files` cannot list.

    Named so the command boundary can catch this one refusal and answer
    it with a sentence, rather than catching every `ValueError` the
    tokenizer or the standard library might raise on the way. A
    `ValueError` subclass because that is what it is to a caller who
    does not know this module's own names: a bad argument.

    The root stays in the message. It is the value the developer just
    typed as `--root` on their own command line, in an instrument under
    `tests/` that reaches no log, event, API body or record, so echoing
    it back discloses nothing the reader does not already have, and
    naming it is what keeps the refusal from reading as a clean tree.
    """


@dataclass(frozen=True)
class Site:
    """One `receiver._name` in one place."""

    path: str
    line: int
    receiver: str
    name: str


def sites(source: str, path: str) -> tuple[list[Site], list[Site]]:
    """The reach-ins in `source`, and the own-state accesses beside them.

    Returns (reach_ins, own_state). Both lists are in source order.
    """
    reached: list[Site] = []
    own: list[Site] = []
    previous: list[tokenize.TokenInfo] = []
    stream = tokenize.generate_tokens(io.StringIO(source).readline)
    for tok in stream:
        if tok.type in (token.NEWLINE, token.NL, token.INDENT, token.DEDENT):
            continue
        if tok.type == token.COMMENT:
            continue
        if (
            tok.type == token.NAME
            and PRIVATE.match(tok.string)
            and len(previous) >= 1
            and previous[-1].type == token.OP
            and previous[-1].string == "."
        ):
            before = previous[-2] if len(previous) >= 2 else None
            receiver = before.string if before is not None else "?"
            site = Site(path, tok.start[0], receiver, tok.string)
            if before is not None and before.type == token.NAME and receiver in OWN_STATE:
                own.append(site)
            else:
                reached.append(site)
        previous.append(tok)
    return reached, own


def tracked(root: Path) -> list[Path]:
    """Every Python file git tracks under `root`, in path order.

    The enumeration is git's rather than the filesystem's, for the
    reason the spellings census gives for its own: an untracked scratch
    file cannot change the answer. That matters more once a committed
    manifest is diffed against this walk, because a stray
    `tests/scratch.py` would otherwise be a red run that blames the
    manifest for a file nobody committed.

    `git -C <root> ls-files -z -- .` lists tracked paths relative to
    `<root>` whatever directory the caller invoked the tool from, which
    is the part an ambient `git ls-files` gets wrong: the same tool run
    from `vinga-server/` and from the repository root would otherwise
    render different paths. The `*.py` filter is applied afterwards,
    since `ls-files` lists everything and this census is a Python
    tokenizer.

    A root git cannot list raises `Unwalkable`, naming the root, rather
    than falling back to a filesystem walk. Two enumerations would be
    two structures that must agree, and the failure a silent fallback
    produces is an empty census, which reads exactly like a clean tree.
    `main` turns it into one line on stderr and a nonzero exit.
    """
    listed = subprocess.run(
        ["git", "-C", str(root), "ls-files", "-z", "--", "."],
        capture_output=True,
        text=True,
    )
    if listed.returncode != 0:
        raise Unwalkable(f"not a directory of the checkout: {root}")
    return sorted(root / name for name in listed.stdout.split("\0") if name.endswith(".py"))


def walk(root: Path) -> tuple[list[Site], list[Site]]:
    """Every site under `root`, in path order.

    A tracked path that is not on disk is skipped: `ls-files` lists a
    file deleted but not yet staged, and a missing file is a fact about
    the working tree rather than about the census.
    """
    reached: list[Site] = []
    own: list[Site] = []
    for path in tracked(root):
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        found, mine = sites(text, str(path.relative_to(root.parent)))
        reached.extend(found)
        own.extend(mine)
    return reached, own


def manifest_of(reached: list[Site]) -> str:
    """One census as the committed manifest reads it: the distinct
    `(path, name)` pairs with the number of sites at each, sorted by
    path and then by name.

    The aggregation is what keeps the artifact still, and what it keeps
    is chosen rather than inherited. Positions go, for the reason the
    spellings manifest drops them: a position moves whenever anything
    above it in a file does, which restages the artifact on rebases for
    no change anybody meant. The count stays, which is where this
    manifest diverges from that precedent on purpose: over the 400
    test-touching revisions the plan measured, eleven of the twenty-eight
    changes moved a count while leaving the pair set alone, so a
    count-free render would have been the weakest of the shapes on offer
    while looking like the safest.

    The receiver is not recorded. `session` in `session._opened_at` is
    lexical rather than semantic, this census resolves no receivers, and
    recording it would split one pair into several the moment a test
    renamed a local.

    The sort is explicit, so the order is a property of the manifest
    rather than of the walk that produced it, and it is a sort on `str`,
    which is codepoint order and locale-independent.
    """
    counts = Counter((site.path, site.name) for site in reached)
    return MANIFEST_HEADER + "".join(
        f"{path}  {name}  {count}\n" for (path, name), count in sorted(counts.items())
    )


def _census(reached: list[Site], own: list[Site]) -> dict[str, object]:
    per_file = Counter(site.path for site in reached)
    per_name = Counter(site.name for site in reached)
    per_pair = Counter((site.path, site.name) for site in reached)
    return {
        "sites": len(reached),
        "names": len(per_name),
        "files": len(per_file),
        "own_state_excluded": len(own),
        "per_file": dict(per_file.most_common()),
        "per_name": dict(per_name.most_common()),
        "per_file_name": [
            {"path": path, "name": name, "count": count}
            for (path, name), count in sorted(
                per_pair.items(), key=lambda item: (item[0][0], -item[1], item[0][1])
            )
        ],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        default=str(Path(__file__).resolve().parent.parent),
        help="the tests directory to walk (default: this file's own)",
    )
    parser.add_argument("--json", action="store_true", help="the whole census as JSON")
    parser.add_argument(
        "--by-site", action="store_true", help="one file:line line per site"
    )
    args = parser.parse_args(argv)

    # The refusal answered as a sentence. A hand-run instrument that
    # rejects its own argument owes the reader the reason, not a stack
    # of frames from the subprocess call that found out; 2 is
    # argparse's own code for an argument it will not accept, so the
    # exit status reads the same whichever half of the boundary refused.
    try:
        reached, own = walk(Path(args.root))
    except Unwalkable as refusal:
        sys.stderr.write(f"{refusal}\n")
        return 2
    census = _census(reached, own)

    if args.json:
        json.dump(
            {**census, "site_list": [asdict(site) for site in reached]},
            sys.stdout,
            indent=2,
        )
        sys.stdout.write("\n")
        return 0

    if args.by_site:
        for site in reached:
            print(f"{site.path}:{site.line}: {site.receiver}.{site.name}")
        print()

    print(
        f"{census['sites']} reach-in sites over {census['names']} names "
        f"across {census['files']} files "
        f"({census['own_state_excluded']} self/cls accesses excluded)"
    )
    print()
    print("By file:")
    for path, count in census["per_file"].items():  # type: ignore[union-attr]
        print(f"  {count:4d}  {path}")
    print()
    print("By name:")
    for name, count in census["per_name"].items():  # type: ignore[union-attr]
        print(f"  {count:4d}  {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
