"""A board swap moves a device's memory rather than orphaning it

`2003_rename_moves_memory` one clause later, and for the same three
reasons it gives. `facts.owner` has said since `2001_agent_memory` that
replacing a device orphans its notes, which was true of every build
until #449's M4: a board swap is now one transaction across the domain
half and this schema, and a device's facts move to the new address with
the record they belong to.

A migration whose whole content is a comment looks like churn, and it is
not, for the reasons 2003 records: the comment is committed DDL, so a
database migrated by an earlier build keeps saying something false until
something changes it there, and
`test_the_baseline_builds_exactly_what_the_tables_declare` compares the
built schema with the declared metadata through Alembic's own
autogeneration, which compares column comments, so editing `schema.py`
alone fails that test. It is forward-only, it moves no row, and the
standing compatibility promise is untouched.

Written by hand rather than autogenerated, for 2003's reason as well.

Revision ID: 2004_a_swap_moves_memory
Revises: 2003_rename_moves_memory
Create Date: 2026-09-11
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2004_a_swap_moves_memory"
down_revision: str | None = "2003_rename_moves_memory"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# What the column says now, and what it said before. Both spelled out
# here rather than imported from `memory.schema`, the rule every
# migration in this chain keeps: a migration is a record of what
# happened, and one reading its comment out of the current declaration
# would rewrite its own history every time that declaration moved.
NOW = (
    "Whose fact this is, read under `scope`: an agent's configured "
    "name, or a device's MAC in canonical form. Neither is orphaned by "
    "the act that changes it: a rename moves an agent's rows in the "
    "transaction that renames the agent, and a board swap moves a "
    "device's in the transaction that puts its record on another board, "
    "so what a household told the speaker in the corner outlives the "
    "hardware it told it to."
)

BEFORE = (
    "Whose fact this is, read under `scope`: an agent's configured "
    "name, or a device's MAC in canonical form. A rename moves an "
    "agent's rows with it, in the transaction that renames the agent, "
    "so a renamed agent keeps what it remembered; replacing a device "
    "orphans that device's notes."
)


def upgrade() -> None:
    op.alter_column(
        "facts",
        "owner",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=NOW,
        existing_comment=BEFORE,
        schema="memory",
    )


def downgrade() -> None:
    op.alter_column(
        "facts",
        "owner",
        existing_type=sa.TEXT(),
        existing_nullable=False,
        comment=BEFORE,
        existing_comment=NOW,
        schema="memory",
    )
