"""Turn a device binding into a device record

`devices` was a MAC holding a list of agent names. #449 makes it a
record: a stable server-minted identity, the name an agent says out
loud about the board it is speaking through, and where that board
stands. The MAC stops being the key and stays `NOT NULL UNIQUE`,
deliberately, because the lookup a board depends on to be served at all
selects `agents` by MAC and that statement does not move.

Hand-written rather than autogenerated. Autogenerate can write the
three `add_column` calls and the key move; it cannot write the two
backfills between them, and a candidate that dropped the backfills
would produce a migration that fails on the first populated database it
meets.

The order is the whole of the correctness here, and each step is
possible only because the one before it ran:

1. `id` arrives nullable, because an existing row has nothing to put in
   it.
2. Every row is minted one. `gen_random_uuid()` is built in since
   Postgres 13 and this build opens nothing older; the dashes come out
   so the stored form is the 32 lowercase hex digits `uuid4().hex`
   writes, which is what the repository mints and what the model's rule
   accepts.
3. `id` becomes `NOT NULL`, which is only true once every row has one.
4. The primary key moves from `mac` to `id`, and `mac` gains the
   unique constraint that keeps it addressable.
5. `name` arrives nullable and is backfilled `Device <full mac>`.
   Full, not truncated: the leading octets are the vendor OUI and a
   fleet shares them, so a truncated default would collide on real
   hardware inside this statement, where there is no good answer. The
   full MAC is unique by construction because `mac` is, so the index in
   step 7 cannot be violated by this backfill.
6. `name` becomes `NOT NULL`.
7. The functional unique index over the FOLDED name. After the
   backfill, so it is created on data that already satisfies it.
8. `location` arrives nullable and stays nullable. A device that is
   nowhere in particular is an ordinary device.

The fold is written out here as a frozen literal rather than imported
from `config.models.device_name_fold_sql`, and that is a decision
rather than an oversight. A migration is a historical record of what
ran; one importing a rule that can later change would make an old
migration reproduce a new behaviour, and a database upgraded last year
would end up with an index nothing here describes.
`tests/unit/test_device_name_fold.py` drives the frozen copy, the live
Python rendering and the live SQL rendering through one corpus, so a
divergence between any of the three is a failing test rather than a
silent one, and it drives the same corpus under a Turkish collation,
which is where a fold that named no collation came apart.

There is no schema staging for a writer from the previous image, and
the reason is a decision this repository has already taken: the
one-replica topology ADR (#316) means a rolling two-version overlap is
not a supported deployment shape. The upgrade is stop-then-migrate. An
older process that kept upserting only `mac` and `agents` through the
old row shape is refused by the `NOT NULL` columns above rather than
silently accepted, which is what the migration test asserts.

Revision ID: 3003_device_record
Revises: 3002_drop_max_tokens_secrets
Create Date: 2026-09-11
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3003_device_record"
down_revision: str | None = "3002_drop_max_tokens_secrets"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "domain"

# The name-uniqueness fold, frozen. Lowercase by the simple mapping,
# runs of Unicode whitespace collapsed to one space, the ends trimmed.
#
# Nothing in this expression is allowed to depend on the locale the
# instance was initialized in, and both halves of it say so in their own
# way.
#
# The case mapping names `pg_c_utf8`, Postgres 17's built-in collation
# provider at locale C.UTF-8, whose case mapping comes from the Unicode
# character database rather than from the host's libc or ICU. A bare
# `lower()` would use the database's default collation instead, and
# under a Turkish one `lower('I')` is `ı` where every other locale
# answers `i`: the index would then disagree with the repository's
# Python fold, approve what the index refuses, and hand the operator a
# sanitized database failure. This is what sets this server's Postgres
# floor at 17, which is the version every deployment artifact here
# already pins; an older instance refuses this statement naming the
# collation rather than building an index that means something else.
#
# The whitespace class is written out character by character rather than
# as `\s`, because what `\s` means to a Postgres regular expression
# depends on the database's ctype for the same reason. The set is
# Unicode's whitespace, which is what Python's own `\s` matches for a
# `str`, and none of its members is `]`, `^`, `-` or `\`, so it is a
# safe bracket expression as written.
FOLD_WHITESPACE = (
    # U+0009 to U+000D, then U+001C to U+001F.
    "\t\n\v\f\r"
    "\x1c\x1d\x1e\x1f"
    # The space, the next line, and the no-break space.
    " \x85\xa0"
    # Ogham space mark; the en/em quad family; line and paragraph
    # separator; narrow and medium mathematical space; ideographic space.
    "\u1680"
    "\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a"
    "\u2028\u2029\u202f\u205f\u3000"
)

FOLD_COLLATION = "pg_c_utf8"

FOLDED_NAME = (
    f"btrim(regexp_replace(lower(name collate {FOLD_COLLATION}), "
    f"'[{FOLD_WHITESPACE}]+', ' ', 'g'), ' ')"
)

NAME_INDEX = "uq_devices_folded_name"


def upgrade() -> None:
    op.add_column(
        "devices", sa.Column("id", sa.Text(), nullable=True), schema=SCHEMA
    )
    op.execute(
        f"update {SCHEMA}.devices set id = replace(gen_random_uuid()::text, '-', '')"
    )
    op.alter_column("devices", "id", nullable=False, schema=SCHEMA)

    op.drop_constraint("pk_devices", "devices", schema=SCHEMA, type_="primary")
    op.create_primary_key("pk_devices", "devices", ["id"], schema=SCHEMA)
    op.create_unique_constraint("uq_devices_mac", "devices", ["mac"], schema=SCHEMA)

    op.add_column(
        "devices", sa.Column("name", sa.Text(), nullable=True), schema=SCHEMA
    )
    op.execute(f"update {SCHEMA}.devices set name = 'Device ' || mac")
    op.alter_column("devices", "name", nullable=False, schema=SCHEMA)
    op.execute(
        f'create unique index "{NAME_INDEX}" on {SCHEMA}.devices (({FOLDED_NAME}))'
    )

    op.add_column(
        "devices", sa.Column("location", sa.Text(), nullable=True), schema=SCHEMA
    )


def downgrade() -> None:
    """Back to a MAC-keyed binding, losing what only the record held.

    Reversible in shape and not in content, which is the honest reading
    of what this migration added: the identities minted above exist
    nowhere else, so a downgrade and a second upgrade give every device
    a new one. An older image meeting a downgraded database finds
    exactly the table it wrote, which is what a downgrade is for.
    """
    op.drop_column("devices", "location", schema=SCHEMA)
    op.execute(f'drop index {SCHEMA}."{NAME_INDEX}"')
    op.drop_column("devices", "name", schema=SCHEMA)
    op.drop_constraint("uq_devices_mac", "devices", schema=SCHEMA, type_="unique")
    op.drop_constraint("pk_devices", "devices", schema=SCHEMA, type_="primary")
    op.create_primary_key("pk_devices", "devices", ["mac"], schema=SCHEMA)
    op.drop_column("devices", "id", schema=SCHEMA)
