"""The conversation store's documentation, rendered from the tables.

One source, two renderings: `comment=` on every column is written once
and read here as the markdown reference committed at
`docs/reference/conversations-schema.md` and as what `vinga-server
conversations schema` prints. The drift test fails on a column with no
comment, which is the same discipline `Field(description=...)` enforces
for the domain models next door.

Everything here is deterministic: no timestamps, no set iteration, and
the column order is the schema's own declaration order. CI regenerates
the committed copy and diffs it byte for byte, so anything that varied
between two runs would turn the lane red on an unrelated change.

Two things a column renderer cannot document, and the honest answer to
each. The event vocabulary that fills `events.name` and `events.fields`
is defined by the event registry, and rendered by the reference beside
this document, which this links rather than restating: fifty-eight
declarations copied here would drift, and the store adds no drift of its
own because it copies field names verbatim. And the
correspondence to OpenTelemetry's GenAI conventions is a mapping
between two vocabularies rather than a property of one column, so it is
written out below where an exporter author reads it once.

Read-only, and deliberately so: nothing here opens a database, reads a
configuration file or needs a key.
"""

import textwrap

from sqlalchemy import Table

from vinga_server.conversations.schema import TABLES

# Where the reference wraps its prose. The tables cannot wrap (a row is
# a line), so only paragraphs go through this.
PROSE_WIDTH = 78

# The event vocabulary's authority, which sits beside this document in
# the same directory and is generated from the registry that declares
# every event.
EVENT_REFERENCE = "events.md"

# The domain model, one directory up from the committed reference. The
# store really holds conversations now: the sessions and turns it always
# held, and the threads those turns belong to. What a session and a
# conversation each mean to a user is that page's, and the reference
# links it rather than restating it. Relative to `docs/reference/`,
# where the reference is committed.
CONCEPTS = "../concepts.md"

# What an exporter maps onto, per the observability ADR's adoption of
# the GenAI conventions "where one exists". Left-hand side is this
# project's field name, right-hand side is the OTel attribute; the third
# column says where the field is found.
GEN_AI: tuple[tuple[str, str, str], ...] = (
    ("input_tokens", "gen_ai.usage.input_tokens", "`turns`, `turns.legs`, the `llm_round` event"),
    (
        "output_tokens",
        "gen_ai.usage.output_tokens",
        "`turns`, `turns.legs`, the `llm_round` event",
    ),
    ("model", "gen_ai.request.model", "the `llm_round`, `llm_retry` and `provider_failed` events"),
    ("type", "gen_ai.provider.name", "the provider-bearing events, and `sessions.providers`"),
    ("host", "server.address", "the provider-bearing events"),
)


def reference() -> str:
    """The whole reference document, rendered from the metadata."""
    lines = [
        "# Conversation store schema reference",
        "",
        "Generated from the SQLAlchemy metadata by `vinga-server conversations",
        "schema`. Do not edit this file by hand: CI regenerates it and fails on any",
        "difference, so an edit here is reverted by the next run. The text of a",
        "column description lives on the table in",
        "`vinga-server/src/vinga_server/conversations/schema.py`.",
        "",
        *_paragraph(
            "The store is the `record` schema of the Postgres database the "
            "`VINGA_DB_*` variables name, beside the domain configuration's `domain` "
            "schema. It holds what was said and what it cost to say it: the session "
            "spine, the threads that span it, the turn timeline both of them project, "
            "the tool invocations a turn issued, the recap checkpoints a thread "
            "accrues, and the decision track underneath all of it. Audio never enters "
            "it. The per-frame endpointer track and the dropped-frame counts stay in "
            "the session capture, which is the recording; this is the queryable "
            "record."
        ),
        "",
        *_paragraph(
            "The schema is `record` and one table inside it is `conversations`, so "
            "SQL spells the thread table `record.conversations`. The schema name "
            "says what the whole of it is; the table name says what one entity is: "
            "a conversation is a durable thread between a user and exactly one "
            "agent, spanning sessions, and a session is one connection episode from "
            "one device. This page keeps the name `conversations-schema.md`, and so "
            "do the command that prints it, the config section that switches the "
            "store on and the events it emits, because those address the store from "
            "outside, where what a reader is after is the conversations in it."
        ),
        "",
        *_paragraph(
            f"A `turns` row names both, which is what makes the session view and the "
            f"thread view two readings of one set of rows rather than two stores: the "
            f"turns of one session can belong to several threads, and one thread's "
            f"turns can come from several sessions. No dialogue is stored twice. "
            f"[The domain concepts page]({CONCEPTS}) says what each means to a user."
        ),
        "",
        *_paragraph(
            "`conversation_milestones` holds the recap checkpoints a conversation "
            "accrues. One row lands when a user is offered a recap of a thread too "
            "long to be picked up whole and says yes: the agent speaks the summary, "
            "and the row is written afterwards, so what the column holds is byte for "
            "byte what was heard. A thread that has one is rebuilt from that "
            "checkpoint plus the turns after its `after_turn`. What it covers is the "
            "inclusive range `from_turn` through `after_turn`; the turns below its "
            "`from_turn` were never read by the summarizer and are outside that "
            "coverage, which is the boundary that stops a bounded recap claiming "
            "turns it omitted. A deployment where nobody has consented to a recap has "
            "an empty table."
        ),
        "",
        "## The compatibility promise",
        "",
        *_paragraph(
            "Table names, column names and event field names are a compatibility "
            "surface. They change only as breaking changes, announced in the "
            "changelog, the same promise the structured events carry. Columns are "
            "added additively and a row written before an addition reads it as null."
        ),
        "",
        "## What is stored, and what the two switches take away",
        "",
        *_paragraph(
            "Recording is off unless `server.conversations.enabled` says otherwise. "
            "Under it, two independent storage switches decide what a row keeps, and "
            "every combination is a supported configuration."
        ),
        "",
        "| Switch | On | Off |",
        "| --- | --- | --- |",
        "| `telemetry` | every measured number, and one `events` row per structured "
        "event | the numeric columns are null and no `events` rows are written |",
        "| `text` | conversation text, and tool names, arguments and results | those "
        "columns are null; the rows still land |",
        "",
        *_paragraph(
            "Three kinds of column survive both switches, and each for a reason worth "
            "stating. The two spines survive because retention and every read key on "
            "them, and a record that cannot be pruned cannot be kept: "
            "`sessions.session` with its device and its timestamps, and the "
            "`conversations` row with its agent, its device and its two timestamps. "
            "Its `title` is the exception and is content, because it is what somebody "
            "said. The structural halves of a turn (`t_ms`, `conversation`, `agent`, "
            "`language`, `tool_calls`) survive because they are neither a measured "
            "number nor conversation text: which thread a turn is on is a fact this "
            "server decided, not a word anybody spoke. And "
            "`sessions.metrics` and `sessions.text` record which way the switches "
            "were set for that session, so a null column is distinguishable from a "
            "column that was never stored; the first keeps the column name the "
            "telemetry switch originally had, because column names are a "
            "compatibility surface and the switch's rename was not a schema change."
        ),
        "",
        *_paragraph(
            "The switches are deployment-wide. Until per-user controls exist, "
            "enabling text storage on a device a household shares stores what guests "
            "say to it, which is the same statement the capture documentation makes "
            "about audio. Attributing a session on a shared device to one member "
            "needs voiceprint identification, which does not exist here yet, so the "
            "units deletion is expressed in are the conversation and the session: "
            "the first is what retention takes whole, and the second is what the "
            "erasure endpoints below address."
        ),
        "",
        *_paragraph(
            "What a marker writes is two transactions rather than one, and which one "
            "a row is in is what it is for. The durable half holds the session row, "
            "the conversations, the turns and their invocations; the lossy half holds "
            "the `events` rows. A durable transaction that fails is retried in place "
            "a few times when the failure is one the database says may simply be made "
            "again, and an events transaction that fails drops and counts its events "
            "in `sessions.dropped` without touching a turn."
        ),
        "",
        *_paragraph(
            "A durable batch that is finally dropped is not silent. The threads it "
            "fed are marked `incomplete` in the durable transaction of the next "
            "marker that commits, and offered again at every marker after that and "
            "at the session's close until the mark lands, so a resume can say the "
            "record has gaps. Riding that transaction rather than one of its own is "
            "what keeps the mark ahead of the writes it is about: a thread with a "
            "known hole in it never reads as whole to somebody who has just been "
            "told a later turn was stored. Two bounds are worth stating. A thread "
            "whose very first "
            "turn was the dropped batch has no row to mark and none is created: an "
            "empty thread would be listed and offered as something to resume with no "
            "dialogue behind it, so the mark waits for the thread's first turn that "
            "does land. And if the database never recovers before the process ends, "
            "neither the tail turns nor the mark persist, and the stored thread "
            "simply ends earlier than the conversation did."
        ),
        "",
        "## Retention and deletion",
        "",
        *_paragraph(
            "`server.conversations.retention_days` defaults to 90, and "
            "`retention_days: 0` keeps everything, which is a deliberate choice "
            "rather than a default: a store without a policy retains forever. What "
            "the window is measured against is a conversation's last activity, "
            "because a conversation is the unit this store retains and deletes. The "
            "pass runs when the server starts and at each session close."
        ),
        "",
        *_paragraph(
            "Three rules, and the order between them is what keeps a live thread "
            "whole. A conversation whose `last_active_at` is older than the window is "
            "deleted whole: its milestones, its turns' invocations, its turns, then "
            "its row. Events are deleted on their own session's `started_at` age "
            "alone, whether or not that session's row survives, because they are "
            "session-scoped telemetry rather than part of the thread. And a session "
            "row older than the window is deleted once no turn names it any more, so "
            "a session that began before the cutoff and holds a thread that is still "
            "being talked to keeps the minimal spine those turns cross-reference "
            "while losing its own events."
        ),
        "",
        *_paragraph(
            "Turns are deleted here and nowhere else. A deployment that never resumes "
            "a conversation sees what it saw before: a thread never spans sessions "
            "there, so its age and its session's coincide and the pass takes them "
            "together."
        ),
        "",
        *_paragraph(
            "Deletion on demand is an act of the API. `DELETE /api/sessions/"
            "{session}` erases one named session, and `DELETE /api/sessions` with at "
            "least one of `session`, `device` and `before` erases every session those "
            "selectors name, combined so that all of them have to match; `before` is "
            "a UTC day and is strict, so a session that began at any moment of the "
            "named day survives it. Both answer the counts they took, per table. The "
            "CLI verbs in front of them are `vinga session delete` and `vinga session "
            "purge`, which are remote callers and reach no database of their own "
            "(#281, #282). `vinga-server conversations purge` was the command this "
            "replaces and is gone."
        ),
        "",
        *_paragraph(
            "One transaction, and erasure outranks every copy the store derived from "
            "what is going. A session's turns are deleted wherever their conversation "
            "is, so a thread that spans sessions honestly keeps a gap rather than "
            "keeping dialogue somebody asked to have removed. In the same "
            "transaction: a conversation whose title came from an erased turn is "
            "renamed from its earliest surviving utterance or loses its title; every "
            "`conversation_milestones` row whose recorded coverage held an erased "
            "turn is deleted, and so is every row descended from it through "
            "`parent`, because a summary of erased content is that content however it "
            "arrived; `last_active_at` moves back when the turn that wrote it is "
            "gone, to the latest fact the store still holds about the survivors, "
            "which is when their sessions began; and a conversation left with no "
            "turns is deleted whole, since what would be left is a title and two "
            "timestamps."
        ),
        "",
        *_paragraph(
            "A session that is still running when its row goes stops being recorded, "
            "because the writer confirms the row inside each of a marker's two "
            "transactions and finds it gone, so neither half can land behind the "
            "deletion. "
            "Capture files are a separate instrument and are never touched by any of "
            "it; the session id is the correlation key for whoever needs to remove "
            "the matching triplet."
        ),
        "",
        *_paragraph(
            "What deletion means is worth stating exactly, because the database "
            "server decides it. A deleted row is invisible to every transaction "
            "that begins after the deletion commits, including the read-only "
            "`vinga_ro` role's. A repeatable-read transaction that was already in "
            "flight when it committed keeps seeing the row until that transaction "
            "ends, which is what multi-version concurrency is and not something "
            "this server can prevent: a query left open in a terminal is one such "
            "transaction. Reclaiming the space the row occupied is the database "
            "server's own storage maintenance (autovacuum), not a per-delete "
            "overwrite, so the interval between the delete and the reclamation is "
            "the instance's to tune rather than this server's to promise. And "
            "copies that have already left the database (a `pg_dump`, a filesystem "
            "snapshot, a replica) are the operator's to manage."
        ),
        "",
        "## Reading it",
        "",
        *_paragraph(
            "There is no analysis command. The store is SQL, and the way to read it "
            "is a live read-only session as `vinga_ro`, the role "
            "`deploy/postgres-init.sql` provisions: it has `SELECT` on every table "
            "in this schema, now and after the next migration, and no access at all "
            "to the domain schema where the stored secrets' ciphertexts live. There "
            "is nothing to copy and nothing to copy safely."
        ),
        "",
        "```bash",
        "psql \"postgresql://vinga_ro@127.0.0.1:5432/vinga\" \\",
        "  -c 'select * from record.turns order by id desc limit 20'",
        "```",
        "",
        *_paragraph(
            "The role carries a `statement_timeout` and an "
            "`idle_in_transaction_session_timeout`, which are not tidiness: a "
            "reader's locks hold off the schema changes a migration makes, so a "
            "session left open in a transaction is what would make the next boot's "
            "migration wait out its lock timeout and refuse."
        ),
        "",
        *_paragraph(
            "The ids on `sessions`, `conversations`, `turns` and `events` are "
            "`bigint` identity "
            "columns, and a sequence never hands out a value twice. That is what "
            "makes them usable as cursors: a client that has read up to id N may ask "
            "for what came after it and cannot be handed a different row under the "
            "same number, even after retention has deleted from the end."
        ),
        "",
        "## The event vocabulary",
        "",
        *_paragraph(
            f"`events.name` and `events.fields` carry the structured event surface, "
            f"whose definition is the [event schema reference]({EVENT_REFERENCE}): "
            f"which events exist, and which fields each one carries. It is not "
            f"restated here, because a second copy of fifty-eight declarations is a "
            f"second copy to drift. The store copies field names verbatim from the "
            f"payload, minus "
            f"`event`, `session` and `device`, which live on the row and on the "
            f"session."
        ),
        "",
        *_paragraph(
            "Some fields never arrive. The writer strips `text` from `heard`, "
            "`replied` and `agent_said`, and `tool` from `tool_call`, before the row "
            "lands, and does so whatever the storage switches say: the `events` table "
            "is metadata-only from its first row."
        ),
        "",
        *_paragraph(
            "The two halves of that strip are in different states, which is worth "
            "knowing before reading a row. The three text fields no longer reach the "
            "events at all, so stripping them is defense in depth on the way in: it "
            "is applied where a row is written and by no read, so it says what lands "
            "in a database this server wrote and nothing about one written before the "
            "narrowing. `tool` does still reach "
            "`tool_call`, on the one branch that names a tool this server authored "
            "itself (a builtin); the strip removes it from the row anyway, so every "
            "name a call carries lives on `tool_invocations` under the text switch "
            "rather than in two tables under two rules. A called tool's name is "
            "content for the same reason its result is, since it is usually a "
            "device's self-description or an MCP server's vocabulary rather than "
            "anything this server authored."
        ),
        "",
        "## The OpenTelemetry GenAI correspondence",
        "",
        *_paragraph(
            "Usage and provider identity use the GenAI semantic conventions adapted "
            "to this project's field style, so an exporter maps by reading one table "
            "rather than by guessing."
        ),
        "",
        "| This project | OpenTelemetry | Where |",
        "| --- | --- | --- |",
        *[f"| `{name}` | `{attribute}` | {where} |" for name, attribute, where in GEN_AI],
        "",
        *_paragraph(
            "`stage` and `provider` keep their own names deliberately. `provider` is "
            "the configured entry's name, a vinga concept with different semantics "
            "from OTel's vendor field, and the convention is adopted where one "
            "exists rather than imposed where one does not."
        ),
        "",
        *_paragraph(
            "A turn's `input_tokens` and `output_tokens` are totals across its "
            "rounds, and after a handover they blend agents that may run different "
            "models. `turns.legs` carries the per-leg counts, and the per-round, "
            "per-model truth is the `llm_round` events in the same database, one join "
            "away."
        ),
        "",
        "## Tables",
        "",
    ]

    for table in TABLES:
        lines += _table_section(table)

    return "\n".join(lines).rstrip("\n") + "\n"


def _table_section(table: Table) -> list[str]:
    lines = [
        f"### `{table.name}`",
        "",
        "| Column | Type | Null | Description |",
        "| --- | --- | --- | --- |",
    ]
    lines += [
        f"| `{column.name}` | `{column.type}` | {_null(column.nullable)} | "
        f"{_cell(column.comment)} |"
        for column in table.columns
    ]
    lines.append("")
    return lines


def _null(nullable: bool) -> str:
    return "yes" if nullable else "no"


def _cell(comment: str | None) -> str:
    """Text inside a table cell. A pipe ends a cell even inside a code
    span, so it is escaped; and an undescribed column is a defect this
    makes visible rather than an empty cell to skim past."""
    if not comment:
        return "**(undescribed)**"
    return " ".join(comment.split()).replace("|", "\\|")


def _paragraph(prose: str) -> list[str]:
    """One paragraph, wrapped. The committed reference is read as a file
    as often as it is rendered, and an unwrapped paragraph makes every
    edit to it a one-line diff of the whole thing.

    Never inside a word or across a hyphen, for the reason the domain
    reference gives: the default would break an identifier in half and a
    code span split over two lines renders with a space in it."""
    return textwrap.wrap(prose, width=PROSE_WIDTH, break_long_words=False, break_on_hyphens=False)


__all__ = ["GEN_AI", "reference"]
