"""Every command spelling in the tree, found once and classified once.

The #223 re-cut respells every word of the configuration grammar, and
the spellings are quoted far outside the module that owns them: in the
example fragments, in both READMEs, in the deploy examples, in the smoke
seeds, in the event catalog's message templates, and in several hundred
lines of prose that are a record of what was true when they were
written. A sweep that misses one leaves a document telling a reader to
type a command this server does not have.

So the sweep is a tool rather than a grep, checked in and run twice.
Before the rename it emits the manifest beside it
(`command-spellings.txt`), the distinct classified vocabulary: one line
per `class  invocation` pair the tree quotes anywhere, however many
sites quote it. That is what makes the sweep reviewable, and it is
reviewable exactly as far as the set goes: a reader can see which
spellings exist and what class each was given, rather than being asked
to trust that the difference was thought about, but a site that leaves
or changes class while a sibling keeps the old pair moves nothing here.
The positions are not recorded, so an edit that only shifts lines
leaves the file alone; the `path:line` of every site is still computed
by `census()`, which is what a reader wanting the sites for a pair
reads, and is named in every guard failure. After the rename the same
code is the standing guard: every match classified `respell` has to
name a command the registered tree actually has, so a stale spelling
fails a test rather than a review.

Regenerating the manifest is `uv run python -m tests.unit.test_command_spellings`
from `vinga-server/`, and the drift test below fails when the committed
copy and a fresh scan disagree.

Three classes, with the rule each is assigned by:

- **`respell`**, an invocation a reader is meant to run today. It moves
  to the new grammar, and the guard holds it to naming a registered
  command.
- **`historical`**, a record of what was true when it was written: the
  plans, the changelog, the feature notes, and the lines of the CLI
  guide that quote the merged grammar as a counterexample, an audit row
  or a recorded tension. Rewriting one would falsify the record.
- **`generated`**, output regenerated from the command tree, so
  respelling it by hand would be wrong twice: it would be reverted by
  the next render, and it would hide the render that should have
  happened.

Four invocation families are recognized, because the grammar is quoted
under four program words: `vinga-server config` (the checkout and
in-image spelling), `vinga config` (the docker shim the CLI reference
defines), `vinga` (the console script this issue adds), and the bare
`config <verb>` shorthand prose uses inside backticks.
"""

import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import pytest

from tests.support.config_cli import registered
from vinga_server.config import cli

# The checkout, found from this file rather than from the working
# directory: the unit lane runs from `vinga-server/` and the sweep is
# over the whole repository.
REPO_ROOT = Path(__file__).resolve().parents[3]

MANIFEST = Path(__file__).with_name("command-spellings.txt")

# What the manifest says about itself, so a reader who opens it first
# knows what it is and what regenerates it.
MANIFEST_HEADER = (
    "# Every command spelling in the tree, classified. Generated by\n"
    "# tests/unit/test_command_spellings.py; do not edit by hand.\n"
    "# Regenerate from vinga-server/ with\n"
    "# `uv run python -m tests.unit.test_command_spellings`.\n"
    "#\n"
    "# One line per distinct pair: class  invocation. No positions, so a\n"
    "# line shift anywhere in the tree leaves this file alone. The sites\n"
    "# of a pair come from the census itself and from any guard failure,\n"
    "# which report them as path:line.\n"
)

# The words the old grammar's top level had, written out because they
# are the thing being retired: after the rename no registered row
# carries them, so nothing can derive them any more. A shorthand match
# is only recognized when the word after `config` is one of these or one
# the tree still has, which is what keeps `config file` and
# `config key` out of a sweep about commands.
_RETIRED_WORDS = frozenset(
    {
        "set",
        "delete",
        "bind-device",
        "add-device",
        "apply",
        "pending",
        "status",
        "prompt",
        "reload",
        "ota-url",
        "set-default-agent",
        "clear-default-agent",
        "set-secret",
        "clear-secret",
        "list",
        "schema",
        "reference",
        "openapi",
        "cli-reference",
        "show",
        "export",
    }
)


def _command_words() -> frozenset[str]:
    """Every word a recognized invocation may open with: the tree's own
    first words, and the ones the re-cut retired."""
    return _RETIRED_WORDS | {row.words[0] for row in cli.COMMANDS}


# One invocation, as a program word and the rest of its line. The
# alternation is longest first, so `vinga-server config` is read as
# itself rather than as the short spelling with a word after it, and
# the lookahead after the bare `vinga` is what keeps it from matching
# inside `vinga-server`.
#
# The rest of the line stops at the characters that end a command line
# in prose or in a shell: a closing backtick, a pipe, a redirect, a
# comment, a separator. What is captured is what a reader would type.
_TERMINATORS = "`'\";|&<>#\n"

_INVOCATION = re.compile(
    r"(?<![\w./-])(vinga-server config|vinga config|vinga)(?![\w-])"
    rf"[ \t]+([^{re.escape(_TERMINATORS)}]*)"
)

# The fourth family: `config <verb>` with no program word in front of
# it, which is how most prose refers to a command. Matched separately
# because it is the same shape with the prefix removed, and the spans
# the family above claimed are skipped so one line is not counted twice.
_SHORTHAND = re.compile(
    rf"(?<![\w./-])(config)(?![\w-])[ \t]+([^{re.escape(_TERMINATORS)}]*)"
)

# The fifth family: a command word no tree has any more, quoted alone.
#
# The four families above recognize an invocation, which is a program
# word and the command after it. Prose refers to a command by its word
# alone at least as often (`bind-device` is the same write for a MAC you
# already know), and a word the re-cut retired is stale in that form
# too: no spelling of the grammar answers to it, so a sentence naming
# one tells a reader to run something that does not exist.
#
# Two conditions, and both are what keep this from matching English. It
# must be inside backticks, which is how this repository quotes a
# command in prose; and it must be one of the COMPOUNDS this grammar
# coined, which is `retired()` below: a word the old top level had, that
# no row or group of the tree carries at any depth, and that is
# hyphenated. `prompt` and `pending` are retired command words and
# ordinary English besides, so a rule that caught them would be a rule
# about the language rather than about the grammar; `bind-device` and
# `set-secret` are words nothing else in any sentence means.
_RETIRED = re.compile(r"`([a-z][a-z0-9]*(?:-[a-z0-9]+)+)`")

# Regenerated from the command tree, so a hand edit here is reverted by
# the next render and hides the render that should have happened.
# The page that is half generated, and the markers that say which
# half. Its head, its installation section and its recovery procedure
# are prose nobody generates, and they prescribe commands like any other
# page: classifying the whole file as generated was what let a stale
# recovery step publish for a milestone.
_HALF_GENERATED = "docs/reference/cli.md"

_GENERATED_REGION = ("<!-- generated: cli reference -->", "<!-- end generated: cli reference -->")

_GENERATED_PATHS = (
    "docs/reference/events.md",
    "docs/reference/domain-config.md",
    "docs/reference/api-openapi.json",
)

# And the generated half of a spike, which is a captured experiment
# rather than a live artifact: neither respelled nor regenerated. Any
# directory named `generated` under a spike, so a second experiment
# inherits the rule rather than needing an entry.
_GENERATED_DIRECTORY = "/generated/"

# A record of what was true when it was written. The spikes' prose is
# here for the same reason their output is above: it reports an
# experiment run on a day, and rewriting it would falsify the report.
_HISTORICAL_PATHS = (
    "docs/plans/",
    "docs/features/",
    "docs/adr/",
    "spikes/",
    "CHANGELOG.md",
    # And the changelog before it is folded. A changelog entry is
    # written as `changelog.d/<issue>-<slug>.md` and moved verbatim into
    # `CHANGELOG.md` on `main` after the merge, so it is the same record
    # under two names and has to carry the same class under both.
    #
    # That is also the property the fold workflow's commit rests on. It
    # moves text between two paths of one class without changing a word
    # of it, so the class and the invocation of every pair are the same
    # before and after, and the distinct-pair manifest cannot move. A
    # bot commit that lands without a CI run of its own therefore cannot
    # stale this artifact, which is asserted rather than assumed in
    # `test_a_fragment_is_a_record_the_way_the_changelog_is`.
    "changelog.d/",
    # And the differential: its transcript is a capture of what the
    # grammar answered on the commit before the rename, and the module
    # beside it names, in the old spelling, exactly what the rename
    # licensed to move. Respelling either would destroy the only thing
    # they are for.
    "vinga-server/tests/unit/data/cli-respelling.txt",
    "vinga-server/tests/unit/test_config_cli_respelling.py",
    # And this tool, which names the retired spellings because naming
    # them is what it is for: its rules are written about `bind-device`
    # and `set-secret`, and its negative fixtures are invocations no
    # tree answers to. A guard that flagged its own examples would be a
    # guard nobody could state a rule in.
    "vinga-server/tests/unit/test_command_spellings.py",
    # And the pre-cutover export, which is a build's own output
    # committed as it was printed. Nothing left in the repository can
    # produce those bytes again: the header it opens with quotes the
    # grammar of the build that wrote it, and the integration lane
    # feeds the file back through today's grammar to prove a kept
    # export still rebuilds a store. Respelling it would destroy the
    # only thing it is for, exactly as respelling the transcript above
    # would. Classified `respell` until #371 asked what it was, which
    # is the misclassification a verb rename exposes.
    "vinga-server/tests/integration/data/pre-cutover-export.yaml",
    # And the CLI guide's source audit, the dated 2026-08-24 walk of
    # four published guides that the guide's practices were
    # dispositioned from. Its rows quote the merged grammar as the
    # evidence of what was audited on that day, which is what they did
    # while they lived in the guide, where the program-word rule below
    # classified every one of them historical. Respelling an audit row
    # would falsify the audit. Unlike the guide it is a record whole,
    # so it is classified by path like the other records rather than by
    # its program word.
    "docs/architecture/cli-guide-audit.md",
)

# The CLI guide is the one page that is both. It states the standard in
# the short spelling and quotes the merged grammar in the long one, as
# counterexamples, audit rows and recorded tensions; the quotes are the
# record and the standard is live. So the page is classified by the
# program word rather than by its path, and this is the rule:
_GUIDE = "docs/architecture/cli-guide.md"

# And its exceptions, which are shapes the page writes in the short
# spelling because the point is the grammar, and which no tree will
# ever answer to: a constructed counterexample is written to be
# rejected. Each is held to still appearing in the page, so an entry
# cannot go stale unnoticed.
_GUIDE_REJECTED = {
    # The address demoted to options, under "Identity addressing".
    "vinga set": "the constructed counterexample of an address written as flags",
}


@dataclass(frozen=True)
class Spelling:
    """One quoted invocation, where it is and what it is."""

    path: str
    line: int
    invocation: str
    kind: str

    def rendered(self) -> str:
        return f"{self.path}:{self.line}  {self.kind}  {self.invocation}"


def tracked() -> list[str]:
    """Every file git tracks, so an untracked scratch file cannot change
    the answer."""
    listed = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        capture_output=True,
        check=True,
        text=True,
    )
    return sorted(name for name in listed.stdout.split("\0") if name)


def _text(path: str) -> str | None:
    """One tracked file's text, or None for one that is not text at all.

    A binary file has no command spelling in it, and a decoding failure
    here is a fact about the file rather than about the sweep.
    """
    try:
        return (REPO_ROOT / path).read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return None


def _generated_region(text: str) -> tuple[int, int] | None:
    """The line numbers the generated markers enclose, or None."""
    lines = text.splitlines()
    opened = closed = None
    for number, line in enumerate(lines, start=1):
        if line.strip() == _GENERATED_REGION[0]:
            opened = number
        if line.strip() == _GENERATED_REGION[1]:
            closed = number
    return (opened, closed) if opened is not None and closed is not None else None


def _classified(path: str, program: str, invocation: str, inside: bool) -> str:
    """Which of the three classes one match belongs to.

    Path first, because a generated artifact is generated whatever it
    quotes and a record is a record whatever it quotes. The guide is
    the one page classified by its program word, for the reason stated
    above it.
    """
    if path.startswith(_GENERATED_PATHS) or _GENERATED_DIRECTORY in f"/{path}":
        return "generated"
    if path == _HALF_GENERATED:
        # Generated between the markers and prose outside them, which is
        # what the page says about itself in its own head.
        return "generated" if inside else "respell"
    if path.startswith(_HISTORICAL_PATHS):
        return "historical"
    if path == _GUIDE:
        if invocation in _GUIDE_REJECTED or program != "vinga":
            return "historical"
        return "respell"
    return "respell"


def _command_line(program: str, rest: str, words: frozenset[str]) -> str | None:
    """One match as the invocation it quotes: the program word and every
    bare word after it.

    The words stop at the first token that is not bare, which is where
    an option, a path, a placeholder or a punctuated end of sentence
    begins. Everything up to there is KEPT, addresses included, because
    the tail is what the guard reads: a row can only be held to taking
    what follows it if what follows it is still here.

    A capture that dropped the words it could not place would be the
    scanner deciding the question the guard exists to ask. `vinga list
    agents` is not `vinga list` with a word after it, it is an
    invocation `list` cannot be given, and a scanner that recorded the
    first would report a document as correct on the strength of having
    edited it. So nothing is discarded, and a site whose prose runs into
    a quoted command is fixed at the site.
    """
    typed = rest.split()
    if not typed or typed[0] not in words:
        return None
    taken: list[str] = []
    for word in typed:
        if not _bare(word):
            break
        taken.append(word)
    return " ".join([program, *taken])


def _bare(word: str) -> bool:
    """Whether a token is a bare command word: letters, digits and
    dashes, opening with a letter. An address, an option, a path and a
    placeholder are each something else."""
    return bool(word) and word[0].isalpha() and word.replace("-", "").isalnum()


def retired(words: frozenset[str]) -> frozenset[str]:
    """The compounds the re-cut took away.

    A word the old top level had, that no row and no group of the tree
    carries at any depth, and that this grammar coined by joining two
    words with a hyphen. The last condition is what makes the set
    checkable rather than a list: an ordinary word cannot be in it, and
    a compound nothing answers to any more can be nothing else.
    """
    live = {word for row in cli.COMMANDS for word in row.words}
    live |= {word for path in cli.GROUPS for word in path}
    return frozenset(word for word in _RETIRED_WORDS if "-" in word and word not in live)


def _matches(path: str, text: str, words: frozenset[str]) -> list[Spelling]:
    """Every recognized invocation in one file, and every retired word."""
    found: list[Spelling] = []
    region = _generated_region(text) if path == _HALF_GENERATED else None
    gone = retired(words)
    for number, line in enumerate(text.splitlines(), start=1):
        inside = region is not None and region[0] < number < region[1]
        claimed: list[tuple[int, int]] = []
        for match in _INVOCATION.finditer(line):
            quoted = _command_line(match.group(1), match.group(2).strip(), words)
            if quoted is None:
                continue
            claimed.append(match.span())
            found.append(
                Spelling(
                    path=path,
                    line=number,
                    invocation=quoted,
                    kind=_classified(path, match.group(1), quoted, inside),
                )
            )
        for match in _SHORTHAND.finditer(line):
            if any(start <= match.start() < end for start, end in claimed):
                continue
            quoted = _command_line("config", match.group(2).strip(), words)
            if quoted is None:
                continue
            found.append(
                Spelling(
                    path=path,
                    line=number,
                    invocation=quoted,
                    kind=_classified(path, "config", quoted, inside),
                )
            )
        for match in _RETIRED.finditer(line):
            if match.group(1) not in gone:
                continue
            found.append(
                Spelling(
                    path=path,
                    line=number,
                    invocation=match.group(1),
                    kind=_classified(path, "word", match.group(1), inside),
                )
            )
    return found


def census() -> list[Spelling]:
    """Every command spelling in the tree, in file and line order."""
    words = _command_words()
    found: list[Spelling] = []
    for path in tracked():
        if path == str(MANIFEST.relative_to(REPO_ROOT)):
            continue
        text = _text(path)
        if text is None:
            continue
        found += _matches(path, text, words)
    return found


def manifest_of(rows: list[Spelling]) -> str:
    """One census as the committed manifest reads it: the distinct
    `class  invocation` pairs, sorted by class and then by invocation.

    The aggregation is what keeps the artifact still. A census carries a
    position for every site, and a position moves whenever anything
    above it in a file does, which restaged all 1,706 lines of the
    manifest on almost every rebase for no change anybody meant. The set
    moves only when a spelling enters the tree, leaves it, or is given
    another class, and each such move is one line git merges cleanly.

    What it costs is stated where the cost falls, in the module head:
    only membership of the pair set is reviewable here.
    """
    pairs = sorted({(row.kind, row.invocation) for row in rows})
    return MANIFEST_HEADER + "".join(f"{kind}  {invocation}\n" for kind, invocation in pairs)


def manifest() -> str:
    """The census as the committed manifest reads."""
    return manifest_of(census())


# The guard
#
# A `respell` match is an invocation a reader is meant to run, so its
# words have to name something the tree has. Which row a command line
# names is `tests.support.config_cli.registered`, the one matcher the
# live lane and the wheel lane read too; what this adds is the other
# thing prose legitimately quotes, which is a group word with no verb
# after it (`the vinga-server config provider secret commands`). A group is
# a node of the same tree, so it is read off the same table.


def _nodes() -> frozenset[tuple[str, ...]]:
    """Every path the registered tree answers to: each row, and each
    group on the way to one."""
    return frozenset(
        row.words[:length]
        for row in cli.COMMANDS
        for length in range(1, len(row.words) + 1)
    )


def _typed(invocation: str) -> tuple[str, ...]:
    """The command words of one invocation: what follows the program
    word."""
    rest = invocation.split()
    for prefix in (("vinga-server", "config"), ("vinga", "config"), ("vinga",), ("config",)):
        if tuple(rest[: len(prefix)]) == prefix:
            return tuple(rest[len(prefix) :])
    return tuple(rest)


def names_something(invocation: str) -> bool:
    """Whether one quoted invocation names a command or a group the
    tree actually has.

    A command is matched by longest registered prefix, because what
    follows its words is an address and an option list. A group is
    matched EXACTLY, because a group takes nothing after it: `vinga
    provider` is a legitimate way for prose to name the noun, and
    `vinga provider frobnicate` is a command that does not exist. A
    leading-prefix rule accepted both, which is the half of this guard
    that was accepting invalid spellings.
    """
    typed = _typed(invocation)
    if registered(typed) is not None:
        return True
    return typed in _nodes()


def test_the_manifest_is_the_census() -> None:
    """The committed classification, held to a fresh scan.

    The manifest is the reviewable half of this sweep, so it is checked
    the way every other generated artifact in this repository is: it is
    rendered again and diffed, and a change to what the tree quotes
    fails here until the manifest is regenerated with it.
    """
    assert MANIFEST.read_text(encoding="utf-8") == manifest()


def test_every_live_spelling_names_a_command_the_tree_has() -> None:
    """The standing guard.

    A `respell` match is an invocation somebody is meant to type. If its
    words do not name a row of the registration table, the document
    naming it is telling a reader to run a command this server does not
    have, which is the failure the whole sweep exists to prevent.
    """
    stale = [
        row.rendered()
        for row in census()
        if row.kind == "respell" and not names_something(row.invocation)
    ]
    assert stale == []


# The half a registered-command guard cannot see
#
# `_command_line` stops at the first token that is not a bare word, so
# `vinga apply -f deployment.yaml` is recorded as `vinga apply`, and the
# guard above then finds `apply` in the tree and passes it. That is the
# right reading for every rename this census had met: a retired word
# stayed retired, so a stale line named nothing.
#
# #371 is the shape that breaks it. It swapped two verbs rather than
# retiring one, so `apply` still names a row and what moved is what the
# row takes: the new `apply` installs the stored configuration and takes
# no document at all. A line left in the old grammar therefore names a
# command that exists and asks it to do something it cannot, which is
# the same failure the census exists to prevent, arriving one layer
# deeper. So the options are read too, off the raw line, for the one
# invocation whose meaning moved.

# What the new `apply` does not take: the document options the old one
# did, and the flag that used to turn its second act off. Compared as
# whole tokens and never as substrings, which is not fussiness: `-f` is
# inside `--force`, and `--force` is a global option every command in
# this grammar takes, so a substring rule reports the one shape an
# operator is most likely to type correctly.
_APPLY_REJECTS = frozenset({"-f", "--file", "--no-reload"})

# One `apply` invocation and everything typed after it, up to where a
# command line ends in prose or in a shell. The tail is the half this
# reads, which is exactly the half the scanner above discards.
_APPLY_TAIL = re.compile(
    r"(?<![\w./-])(?:vinga-server config|vinga config|vinga|config)[ \t]+apply(?![\w-])"
    rf"([^{re.escape(_TERMINATORS)}]*)"
)


def _span(lines: list[str], first: int) -> str:
    """One command as it was typed, which is not always one line.

    A shell continues a command onto the next line with a trailing
    backslash, and the documents here use that for exactly the invocation
    this reads: a long command with its options underneath it. Reading
    the physical line alone would find the verb and none of what follows
    it, which is the same blindness the scanner above has and this exists
    to close.

    Joined with a single space and the backslashes dropped, so what comes
    back is the token sequence a shell would see. `first` is a 1-based
    line number, as a `Spelling` records it.
    """
    taken: list[str] = []
    number = first - 1
    while number < len(lines):
        line = lines[number]
        taken.append(line.rstrip().removesuffix("\\").strip())
        if not line.rstrip().endswith("\\"):
            break
        number += 1
    return " ".join(taken)


def _carries_a_document(span: str) -> bool:
    """Whether one command span asks an `apply` for something it cannot
    take.

    The tail is split the way a shell splits it and each token is read as
    the option it names, so `--file=deployment.yaml` is `--file` and
    `--force` is itself.
    """
    return any(
        token.split("=", 1)[0] in _APPLY_REJECTS
        for match in _APPLY_TAIL.finditer(span)
        for token in match.group(1).split()
    )


def option_bearing_applies(path: str, text: str) -> list[str]:
    """Every live `apply` in one file written the way the old one was.

    Classified through the same scanner as everything else, so the
    historical records and the generated artifacts are exempt here for
    the reasons they are exempt there.
    """
    lines = text.splitlines()
    return [
        row.rendered()
        for row in _matches(path, text, _command_words())
        if row.kind == "respell"
        and _typed(row.invocation) == ("apply",)
        and _carries_a_document(_span(lines, row.line))
    ]


def test_no_live_apply_is_written_the_way_the_old_one_was() -> None:
    """The standing guard over the stale half of the verb swap."""
    stale = [
        row
        for path in tracked()
        if path != str(MANIFEST.relative_to(REPO_ROOT)) and (text := _text(path)) is not None
        for row in option_bearing_applies(path, text)
    ]

    assert stale == []


# The shapes the option guard is held to, one per row
#
# Written as pages rather than as file paths, for the reason the cases
# at the foot of this module are: a fixture cannot go stale when the site
# it was found at is fixed, and what is being checked is the rule.
#
# The two halves are equally load-bearing. A shape it must flag is a
# document left in the old grammar; a shape it must not flag is a
# document written correctly, and a guard that cried wolf over
# `apply --force` would be a guard somebody turns off.
STALE_APPLIES = [
    ("the document option", "run `vinga apply -f deployment.yaml`", True),
    ("the long document option", "run `vinga config apply --file deployment.yaml`", True),
    ("the deleted flag", "run `vinga apply --no-reload -f -`", True),
    ("an attached value", "run `vinga apply --file=deployment.yaml`", True),
    (
        "the document option a line down",
        "vinga apply \\\n  -f deployment.yaml",
        True,
    ),
    (
        "the long document option a line down",
        "vinga-server config apply \\\n  --file deployment.yaml",
        True,
    ),
    (
        "the deleted flag a line down",
        "vinga apply \\\n  --no-reload",
        True,
    ),
    ("the global force flag", "run `vinga apply --force`", False),
    ("the global force flag a line down", "vinga apply \\\n  --force", False),
    ("the address option", "run `vinga apply --api-url https://voice.example/api`", False),
    ("the install alone", "run `vinga apply`", False),
    ("the write that takes a document", "run `vinga import -f deployment.yaml`", False),
]


@pytest.mark.parametrize(
    ("page", "flagged"),
    [(page, flagged) for _, page, flagged in STALE_APPLIES],
    ids=[what for what, _, _ in STALE_APPLIES],
)
def test_the_option_guard_reads_whole_tokens_and_whole_commands(
    page: str, flagged: bool
) -> None:
    """The guard held to going red and to staying quiet.

    `-f` is a substring of `--force`, which every command of this
    grammar takes, so the tokens are compared whole. And a command
    continued onto the next line is one command, so the span is read
    rather than the line: the shape a deployment script writes is
    exactly the shape a line-at-a-time rule cannot see.
    """
    assert bool(option_bearing_applies("docs/somewhere.md", page)) is flagged, page


def test_the_guides_rejected_shapes_still_appear() -> None:
    """The guide's exemptions, held to being about something.

    An entry naming a shape the page has since stopped writing would
    quietly widen what a `respell` match is allowed to be.
    """
    quoted = {row.invocation for row in census() if row.path == _GUIDE}
    assert sorted(_GUIDE_REJECTED) == sorted(set(_GUIDE_REJECTED) & quoted)


# What a generated document may be spelled as
#
# One spelling, whatever rendered it, which is the rule the whole
# canonical constant exists for: a document may no more vary with the
# invocation than with the terminal. The drift checks cannot see this.
# They regenerate an artifact and diff it, so a description carrying the
# wrong program word moves the committed copy and the fresh render
# together and passes green forever.
#
# One exception, and it is a different fact rather than a loosening.
# `events.md` renders the event catalog's message templates, and those
# are sentences a SERVER composes: a server runs inside the image, where
# `vinga-server` is what a shell answers to, and the settled rule sends
# such a sentence to the long spelling. What is generated there is the
# document, not the sentence.
_SERVER_COMPOSED = ("docs/reference/events.md",)

# And what the rule is not about at all: a captured experiment. The
# spike artifacts under `spikes/` were rendered on the day they were
# run, against the grammar of that day, and nothing regenerates them.
# Holding a frozen capture to today's spelling would be asking a
# photograph to age.
_CAPTURED = ("spikes/",)


def mis_spelled(rows: list[Spelling]) -> list[str]:
    """Every generated invocation that is not in the canonical
    spelling."""
    return [
        row.rendered()
        for row in rows
        if row.kind == "generated"
        and not row.path.startswith(_SERVER_COMPOSED + _CAPTURED)
        and not row.invocation.startswith(f"{cli.PROGRAM} ")
    ]


def test_a_generated_document_carries_one_spelling() -> None:
    """The standing guard over the artifacts this repository renders."""
    assert mis_spelled(census()) == []


def test_the_long_spelling_inside_a_generated_region_is_flagged() -> None:
    """And the guard held to going red, which is the half a passing
    assertion cannot show: this is the text the review round found in
    two committed artifacts, and it is a finding rather than a pass."""
    page = "\n".join(
        [
            _GENERATED_REGION[0],
            "| `tools` | which is the name `vinga-server config status` shows |",
            _GENERATED_REGION[1],
        ]
    )

    flagged = mis_spelled(_matches(_HALF_GENERATED, page, _command_words()))

    assert [row.split("  ")[-1] for row in flagged] == ["vinga-server config status"]


def test_a_server_composed_document_keeps_the_long_spelling() -> None:
    """The exception, held to being one: an event message names the
    invocation a server has, and the guard leaves it alone."""
    page = "device %s has no agent; bind it with: vinga-server config device pending claim"

    assert mis_spelled(_matches("docs/reference/events.md", page, _command_words())) == []


def test_every_class_is_one_of_the_three() -> None:
    """The vocabulary, kept closed. A fourth class would be a
    classification nobody stated a rule for."""
    assert {row.kind for row in census()} <= {"respell", "historical", "generated"}


if __name__ == "__main__":  # pragma: no cover - the regeneration entry point
    MANIFEST.write_text(manifest(), encoding="utf-8")
    sys.stdout.write(f"wrote {MANIFEST}\n")


# The shapes this recognizer got wrong, kept as cases
#
# Every one of these is a real miss or a real false accept, found by
# holding the guard against the tree it guards. Written as synthetic
# lines rather than as file paths, so a fixture cannot go stale when the
# site it was found at is fixed, and so what is being checked is the
# rule rather than today's tree.

WORDS = _command_words()


def found_in(line: str, path: str = "docs/somewhere.md") -> list[Spelling]:
    return _matches(path, line, WORDS)


def test_a_quote_ends_a_command_line() -> None:
    """The miss that let a stale runtime refusal publish: the sentence
    was assembled in an f-string, the closing quote was not a terminator,
    and the last word came out as `set"`, which is no command word, so
    the whole line was dropped."""
    [found] = found_in('            f"vinga-server config set"')

    assert found.invocation == "vinga-server config set"


def test_a_backtick_opens_a_shorthand_rather_than_forbidding_one() -> None:
    """The family claimed to cover prose in backticks and then excluded
    exactly that: a backtick before `config` made the match fail."""
    [found] = found_in("written one at a time with `config apply`, which is")

    assert found.invocation == "config apply"


def test_a_retired_compound_is_recognized_on_its_own() -> None:
    """Prose names a command by its word alone at least as often as by
    an invocation, and a compound this grammar coined and then took
    away is stale in that form too."""
    [found] = found_in("`bind-device` is the same write for a MAC you know")

    assert found.invocation == "bind-device"
    assert not names_something(found.invocation)


@pytest.mark.parametrize(
    "line",
    [
        "the prompt an agent is sent",
        "a `pending` device is one waiting",
        "`mcp-server` is a noun of the grammar",
        "`default-agent` too",
    ],
    ids=["an ordinary word", "a retired word that is ordinary", "a noun", "another noun"],
)
def test_the_retired_family_matches_neither_english_nor_a_live_noun(line: str) -> None:
    """The two conditions that keep it a rule about the grammar rather
    than about the language: backticks, and a compound nothing answers
    to any more."""
    assert [row.invocation for row in found_in(line)] == []


def test_the_half_generated_page_is_classified_by_its_markers() -> None:
    """`cli.md` is prose above the marker and rendering below it.
    Classifying the whole file as generated is what let a stale recovery
    step publish for a milestone: nothing regenerates that half, so
    nothing would ever have corrected it."""
    page = "\n".join(
        [
            "prose: vinga-server config apply -f deployment.yaml",
            _GENERATED_REGION[0],
            "rendered: vinga-server config apply -f deployment.yaml",
            _GENERATED_REGION[1],
            "prose again: vinga-server config apply -f deployment.yaml",
        ]
    )

    assert [row.kind for row in _matches(_HALF_GENERATED, page, WORDS)] == [
        "respell",
        "generated",
        "respell",
    ]


@pytest.mark.parametrize(
    ("invocation", "names"),
    [
        ("vinga provider", True),
        ("vinga provider secret", True),
        ("vinga provider frobnicate", False),
        ("vinga provider secret frobnicate", False),
        ("vinga frobnicate", False),
        ("vinga provider set llm local", True),
        ("vinga-server config device pending list", True),
        ("vinga device pending frobnicate", False),
    ],
)
def test_a_group_is_named_exactly_and_a_command_by_its_words(
    invocation: str, names: bool
) -> None:
    """A command is matched by longest registered prefix, because what
    follows its words is an address. A group takes nothing after it, so
    it is matched exactly: the leading-prefix rule accepted
    `vinga provider frobnicate`, which is the half of this guard that
    was accepting invalid spellings rather than missing valid ones."""
    assert names_something(invocation) is names


@pytest.mark.parametrize(
    ("line", "invocation", "names"),
    [
        ("run `vinga show provider llm claude` now", "vinga show provider llm claude", False),
        ("run `vinga export agent assistant` now", "vinga export agent assistant", False),
        (
            "run `vinga-server config show device aa-bb` now",
            "vinga-server config show device aa-bb",
            False,
        ),
        ("run `vinga list agents` now", "vinga list agents", False),
        ("run `vinga status mcp-server` now", "vinga status mcp-server", False),
        ("run `vinga provider show llm claude` now", "vinga provider show llm claude", True),
        ("run `vinga agent export assistant` now", "vinga agent export assistant", True),
        ("run `vinga device show aa-bb` now", "vinga device show aa-bb", True),
        (
            "run `vinga provider secret set llm claude token` now",
            "vinga provider secret set llm claude token",
            True,
        ),
        ("run `vinga agent set kids` now", "vinga agent set kids", True),
        ("run `vinga show` now", "vinga show", True),
        ("run `vinga export` now", "vinga export", True),
    ],
    ids=[
        "the retired verb-first show",
        "the retired verb-first export",
        "the retired show device",
        "a flat read given a subject",
        "a flat read given a noun",
        "the respelled show",
        "the respelled export",
        "the respelled device read",
        "three words and three identities",
        "a write with an identity",
        "the flat read, alone",
        "the flat export, alone",
    ],
)
def test_a_word_a_flat_verb_cannot_take_makes_the_spelling_stale(
    line: str, invocation: str, names: bool
) -> None:
    """The other half of the same hole, and the one that survived two
    milestones.

    Matching the longest registered prefix and stopping there reads
    `show provider llm claude` as the flat `show` row with three words
    nobody asked about, so every retired verb-first spelling in the tree
    passed this guard while naming a command the grammar no longer has.
    What the matcher asks now is whether the row could be GIVEN what
    follows it, counted against the positional arguments the built tree
    declares, so a flat read carrying an address is stale and a noun's
    read carrying the same address is not.

    Driven through the SCANNER and not through `names_something` alone,
    which is what the first version of these cases got wrong: they
    asserted about a string somebody had already decided the shape of,
    so a capture that quietly dropped the words in question would have
    left every one of them green. Here the line is what a document
    contains, the capture is asserted to hold the whole invocation
    including its tail, and the verdict is taken from that.
    """
    [found] = found_in(line)

    assert found.invocation == invocation
    assert names_something(found.invocation) is names


# The fragment a changelog entry arrives as
#
# A changelog entry is written as `changelog.d/<issue>-<slug>.md` and
# folded into `CHANGELOG.md` on `main` after the merge. Both paths are
# records, and the fold is a verbatim move between them, so the property
# stated beside `changelog.d/` in `_HISTORICAL_PATHS` is asserted here:
# the same text under either path is the same class, so the distinct
# pair the manifest carries is the same pair before and after a fold.


def test_a_fragment_is_a_record_the_way_the_changelog_is() -> None:
    """The fold cannot stale the census.

    An entry quoting a command is historical while it waits in
    `changelog.d/` and historical once it is in `CHANGELOG.md`, so the
    bot commit that moves it renders the manifest byte-identical. That
    is what lets the fold commit land without a CI run of its own.
    """
    fragment = found_in(LIVE, "changelog.d/467-changelog-fragments.md")
    folded = found_in(LIVE, "CHANGELOG.md")

    assert [row.kind for row in fragment] == ["historical"]
    assert manifest_of(fragment) == manifest_of(folded)


# What the manifest aggregates, and what it aggregates away
#
# Properties of the rendering rather than of today's tree, so they are
# driven through the scanner over synthetic pages: the same sites in any
# order render the same bytes, one pair quoted in two files renders one
# line, one invocation given two classes renders two, and a site that
# leaves renders no diff at all while a sibling keeps its pair.

# One live invocation, quoted the way a document quotes one. Its class
# is the file it is found in, which is what lets the same line stand for
# a respell site and a historical one.
LIVE = "run `vinga agent set kids` now"


def _entries(rendered: str) -> list[str]:
    """One rendered manifest's lines below its header."""
    assert rendered.startswith(MANIFEST_HEADER)
    return rendered.removeprefix(MANIFEST_HEADER).splitlines()


def test_one_pair_quoted_in_two_files_is_one_manifest_line() -> None:
    """The aggregation, which is the whole of the change: two sites of
    one pair are one line, and the order they were scanned in is not in
    the artifact either, so a rebase cannot reorder it."""
    rows = found_in(LIVE, "docs/one.md") + found_in(LIVE, "docs/two.md")

    assert len(rows) == 2
    assert _entries(manifest_of(rows)) == ["respell  vinga agent set kids"]
    assert manifest_of(list(reversed(rows))) == manifest_of(rows)


def test_one_invocation_under_two_classes_is_two_manifest_lines() -> None:
    """And the half the set must not collapse: the class is what the
    manifest is reviewed for, so the same words given two classes are
    two entries rather than one."""
    rows = found_in(LIVE, "docs/one.md") + found_in(LIVE, "docs/plans/2026-01-01-a-plan.md")

    assert _entries(manifest_of(rows)) == [
        "historical  vinga agent set kids",
        "respell  vinga agent set kids",
    ]


def test_a_site_leaving_a_pair_another_site_keeps_moves_nothing() -> None:
    """The accepted limitation, asserted rather than described.

    A distinct set makes membership of the set reviewable and nothing
    else. When two sites carry one pair, dropping one of them renders
    byte-identical, and reclassifying one leaves the old class standing
    on the strength of the sibling: both are real losses of per-site
    review granularity, priced when the positions were dropped. The
    property is pinned here so no later documentation can quietly
    recover the stronger claim that every classification change shows up
    as a diff.
    """
    both = found_in(LIVE, "docs/one.md") + found_in(LIVE, "docs/two.md")
    one_absent = found_in(LIVE, "docs/one.md")
    one_reclassified = found_in(LIVE, "docs/one.md") + found_in(
        LIVE, "docs/plans/2026-01-01-a-plan.md"
    )

    assert manifest_of(one_absent) == manifest_of(both)
    assert "respell  vinga agent set kids" in _entries(manifest_of(one_reclassified))
